export const DEMO_USERS = [
  {
    id: 'skipper',
    role: 'skipper',
    officerType: null,
    email: 'skipper@orca.gov.in',
    password: 'orca123',
    name: 'Capt. Rajesh Mondal',
    title: 'Vessel Skipper / Commercial Mariner',
    cadre: 'Bengal Coastal Fishermen Cooperative Federation',
    vesselOrStation: 'FB Maa Ganga (WB-24-M-104)',
    badgeOrReg: 'IND-WB-24-00918',
    badgeText: 'SKIPPER',
    accentColor: 'emerald',
    badgeClass: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    borderHover: 'hover:border-emerald-500',
    btnClass: 'bg-emerald-600 hover:bg-emerald-700 text-white',
    deckName: 'Wheelhouse Fishing Advisory Deck',
    keyCapabilities: [
      'Dawn sailing Go / No-Go safety verdict',
      'Optimal sector with NavIC GPS coordinates',
      'Diesel trip economics & return-on-fuel calculator',
      'Vernacular voice advisories (English, Bengali, Hindi)',
      'Quayside digital catch log submission'
    ]
  },
  {
    id: 'coast_guard',
    role: 'officer',
    officerType: 'coast_guard',
    email: 'officer.coastguard@orca.gov.in',
    password: 'orca123',
    name: 'Cmdr. Vikram Rathore',
    title: 'Indian Coast Guard Patrol Commander',
    cadre: 'Ministry of Defence · Maritime Surveillance Unit',
    vesselOrStation: 'ICGS Varad (Fast Patrol Vessel)',
    badgeOrReg: 'ICG-OFF-8821',
    badgeText: 'COAST GUARD',
    accentColor: 'orange',
    badgeClass: 'bg-orange-100 text-orange-800 border-orange-300',
    borderHover: 'hover:border-orange-500',
    btnClass: 'bg-orange-600 hover:bg-orange-700 text-white',
    deckName: 'Coastal Patrol & Maritime Enforcement Deck',
    keyCapabilities: [
      'Uniform 61-day Bay of Bengal fishing ban enforcement',
      'UNCLOS 2014 India–Bangladesh IMBL 5 NM geofence',
      'Live Bay of Bengal AIS vessel radar & collision watch (<6 NM)',
      'Real-time violation logging & automated detention alerts'
    ]
  },
  {
    id: 'incois_scientist',
    role: 'officer',
    officerType: 'incois_scientist',
    email: 'officer.incois@orca.gov.in',
    password: 'orca123',
    name: 'Dr. Ananya Sen',
    title: 'INCOIS Oceanographic Scientist / PFZ Officer',
    cadre: 'INCOIS · Ministry of Earth Sciences (MoES)',
    vesselOrStation: 'INCOIS Oceanographic Research Vessel',
    badgeOrReg: 'GOI-INCOIS-PFZ-02',
    badgeText: 'INCOIS PFZ',
    accentColor: 'teal',
    badgeClass: 'bg-teal-100 text-teal-800 border-teal-300',
    borderHover: 'hover:border-teal-500',
    btnClass: 'bg-[#007A78] hover:bg-[#006361] text-white',
    deckName: 'Satellite Oceanography & Telemetry Verification Deck',
    keyCapabilities: [
      'Live Copernicus Marine & NOAA GFS telemetry ingestion',
      'Official INCOIS Baseline Match Verification (98% confidence)',
      'Potential Fishing Zone (PFZ) thermal front gradients',
      'Official MoES clearance authentication & broadcast'
    ]
  },
  {
    id: 'researcher',
    role: 'researcher',
    officerType: null,
    email: 'researcher@incois.res.in',
    password: 'orca123',
    name: 'Dr. Priya Sharma',
    title: 'Marine Research Scientist & Oceanographer',
    cadre: 'CSIR · National Institute of Oceanography (NIO)',
    vesselOrStation: 'RV Sindhu Sadhana Observer · Digha Marine Station',
    badgeOrReg: 'NIO-RES-409',
    badgeText: 'RESEARCHER',
    accentColor: 'amber',
    badgeClass: 'bg-amber-100 text-amber-800 border-amber-300',
    borderHover: 'hover:border-amber-500',
    btnClass: 'bg-amber-600 hover:bg-amber-700 text-white',
    deckName: 'Hydrographic Multi-Agent Lab & Sensitivity Deck',
    keyCapabilities: [
      'Interactive multi-agent weight sliders (Ocean, Weather, History, Sustain)',
      '12-month longitudinal CMFRI & satellite time-series',
      'Hydrographic Chart IN-351 bathymetric sounding depths',
      'One-click scan audit export in JSON & CSV formats'
    ]
  },
  {
    id: 'fisheries_officer',
    role: 'officer',
    officerType: 'fisheries_officer',
    email: 'officer.fisheries@orca.gov.in',
    password: 'orca123',
    name: 'Sunil Roy',
    title: 'State Marine Fisheries Enforcement Officer',
    cadre: 'Directorate of Marine Fisheries, Govt of West Bengal',
    vesselOrStation: 'Fisheries Vigilance Patrol-04 · Shankarpur Harbor',
    badgeOrReg: 'WB-FISH-7734',
    badgeText: 'FISHERIES',
    accentColor: 'blue',
    badgeClass: 'bg-blue-100 text-blue-800 border-blue-300',
    borderHover: 'hover:border-blue-500',
    btnClass: 'bg-blue-600 hover:bg-blue-700 text-white',
    deckName: 'Fisheries Conservation & Compliance Deck',
    keyCapabilities: [
      'West Bengal Marine Fishing Regulation Act (MFRA) monitoring',
      'Sundarbans Biosphere & Lothian Island MPA sanctuary protection',
      'Legal mesh size compliance and mechanized trawler registration',
      'Incident inspection audit and fine dispatching'
    ]
  },
  {
    id: 'port_crew',
    role: 'port_crew',
    officerType: null,
    email: 'portmaster@sagar.port.gov.in',
    password: 'orca123',
    name: 'Capt. B. K. Halder',
    title: 'Port Master & Quay Logistics Operator',
    cadre: 'Kolkata Port Trust & Sagar Anchorage Maritime Board',
    vesselOrStation: 'Pilot Vessel Sagar Sandhya · Sagar Roads Anchorage',
    badgeOrReg: 'PORT-SAGAR-01',
    badgeText: 'PORT MASTER',
    accentColor: 'slate',
    badgeClass: 'bg-slate-200 text-slate-800 border-slate-300',
    borderHover: 'hover:border-slate-500',
    btnClass: 'bg-slate-700 hover:bg-slate-800 text-white',
    deckName: 'Harbor Quay-Side Logistics Console',
    keyCapabilities: [
      'Real-time harbor fish biomass inflow forecasts (7-day outlook)',
      'Cold storage capacity and ice flake distribution planning',
      'Verified quayside catch landing ledger entry',
      'Returning mechanized trawler ETA and draft clearance'
    ]
  },
  {
    id: 'visitor',
    role: 'public',
    officerType: null,
    email: 'visitor@orca.in',
    password: 'orca123',
    name: 'Aarav Mehta',
    title: 'Curious Visitor / General Public',
    cadre: 'Ocean Enthusiast · Public Explainer Mode',
    vesselOrStation: 'Visitor & Education Deck · Bay of Bengal',
    badgeOrReg: 'VISITOR-GUEST',
    badgeText: 'VISITOR',
    accentColor: 'sky',
    badgeClass: 'bg-sky-100 text-sky-800 border-sky-300',
    borderHover: 'hover:border-sky-500',
    btnClass: 'bg-sky-600 hover:bg-sky-700 text-white',
    deckName: 'Interactive Explainer & Simulation Deck',
    keyCapabilities: [
      'Guided walkthrough of all 4 AI agents & safety veto',
      'Try-It-Yourself annual season & ban slider',
      'Jargon-free translations alongside real satellite metrics',
      'Interactive zone prediction challenge',
      'Zero-friction entry without maritime jargon or setup'
    ]
  }
]

