/**
 * hydrography.js
 * -----------------------------------------------------------------------------
 * Nautical Hydrographic Chart Registries and Bathymetric Transect Profiles
 * for India's 9 Coastal Maritime Corridors.
 * -----------------------------------------------------------------------------
 */

export const CORRIDORS = [
  {
    id: 'kolkata-haldia',
    portId: 'kolkata-haldia',
    regionId: 'bay-of-bengal',
    name: 'West Bengal',
    shortName: 'Bengal',
    state: 'West Bengal',
    corridorName: 'Hooghly Deltaic Shelf',
    chartNumber: 'Chart IN-351',
    chartTitle: 'Chart IN-351: Northern Bengal Shelf & Canyon Head',
    chartMeta: "Scale 1:150,000 · Mercator Projection · LAT 20°40'N – 21°55'N · LONG 86°50'E – 89°20'E",
    beaconStatus: 'Acoustic Beacon 74 Online',
    shelfProfile: 'deltaic',
    shelfDescription: 'Gentle estuarine silt & clay continental shelf formed by the Ganges-Brahmaputra sediment plume.',
    maxDepth: 35,
    maxDist: 25,
    depthGraticules: [0, 10, 20, 30],
    distMarkers: [5, 10, 15, 20, 25],
    defaultZoneId: 'digha',
    subZoneIds: ['digha', 'shankarpur', 'junput', 'sagar-island', 'frazerganj', 'kakdwip']
  },
  {
    id: 'paradip',
    portId: 'paradip',
    regionId: 'bay-of-bengal',
    name: 'Odisha',
    shortName: 'Odisha',
    state: 'Odisha',
    corridorName: 'Mahanadi Terrigenous Plume',
    chartNumber: 'Chart IN-352',
    chartTitle: 'Chart IN-352: Mahanadi Delta & Paradip Roads',
    chartMeta: "Scale 1:150,000 · Mercator Projection · LAT 20°10'N – 20°35'N · LONG 86°30'E – 86°55'E",
    beaconStatus: 'Acoustic Beacon 68 Online',
    shelfProfile: 'terrigenous',
    shelfDescription: 'Alluvial river plume delta and sand wave shelf adjoining Gahirmatha marine buffer.',
    maxDepth: 30,
    maxDist: 20,
    depthGraticules: [0, 10, 20, 30],
    distMarkers: [5, 10, 15, 20],
    defaultZoneId: 'paradip-outer',
    subZoneIds: ['paradip-outer', 'mahanadi-mouth', 'jatadhari-estuary']
  },
  {
    id: 'visakhapatnam',
    portId: 'visakhapatnam',
    regionId: 'bay-of-bengal',
    name: 'Andhra Pradesh',
    shortName: 'Andhra',
    state: 'Andhra Pradesh',
    corridorName: 'Visakhapatnam Continental Slope',
    chartNumber: 'Chart IN-308',
    chartTitle: 'Chart IN-308: Dolphin’s Nose & Andhra Deep',
    chartMeta: "Scale 1:150,000 · Mercator Projection · LAT 17°30'N – 17°55'N · LONG 83°10'E – 83°45'E",
    beaconStatus: 'Acoustic Beacon 52 Online',
    shelfProfile: 'steep-slope',
    shelfDescription: 'Narrow coastal shelf rapidly plunging into deep oceanic waters off Dolphin’s Nose.',
    maxDepth: 55,
    maxDist: 20,
    depthGraticules: [0, 15, 30, 45],
    distMarkers: [5, 10, 15, 20],
    defaultZoneId: 'vizag-dolphins-nose',
    subZoneIds: ['vizag-dolphins-nose', 'gangavaram-roads', 'rishikonda-bank']
  },
  {
    id: 'chennai',
    portId: 'chennai',
    regionId: 'bay-of-bengal',
    name: 'Tamil Nadu',
    shortName: 'Tamil Nadu',
    state: 'Tamil Nadu',
    corridorName: 'Coromandel Siliceous Shelf',
    chartNumber: 'Chart IN-313',
    chartTitle: 'Chart IN-313: Coromandel Coast & Chennai Approaches',
    chartMeta: "Scale 1:150,000 · Mercator Projection · LAT 13°00'N – 13°30'N · LONG 80°10'E – 80°35'E",
    beaconStatus: 'Acoustic Beacon 41 Online',
    shelfProfile: 'siliceous',
    shelfDescription: 'Gradual sandy-mud continental shelf with longshore quartz sand bars.',
    maxDepth: 35,
    maxDist: 20,
    depthGraticules: [0, 10, 20, 30],
    distMarkers: [5, 10, 15, 20],
    defaultZoneId: 'chennai-kasimedu',
    subZoneIds: ['chennai-kasimedu', 'ennore-shoals', 'marina-outer-bank']
  },
  {
    id: 'mumbai',
    portId: 'mumbai',
    regionId: 'arabian-sea',
    name: 'Maharashtra',
    shortName: 'Maharashtra',
    state: 'Maharashtra',
    corridorName: 'North Konkan Basaltic Shelf',
    chartNumber: 'Chart IN-211',
    chartTitle: 'Chart IN-211: Mumbai Approaches & Konkan Shelf',
    chartMeta: "Scale 1:150,000 · Mercator Projection · LAT 18°35'N – 19°05'N · LONG 72°35'E – 73°00'E",
    beaconStatus: 'Acoustic Beacon 88 Online',
    shelfProfile: 'basaltic',
    shelfDescription: 'Deccan trap basaltic rock foundation draped in productive dark olive-green mud.',
    maxDepth: 45,
    maxDist: 25,
    depthGraticules: [0, 10, 20, 30, 40],
    distMarkers: [5, 10, 15, 20, 25],
    defaultZoneId: 'sassoon-dock-offshore',
    subZoneIds: ['sassoon-dock-offshore', 'mumbai-floating-light', 'alibaug-shoals']
  },
  {
    id: 'cochin',
    portId: 'cochin',
    regionId: 'arabian-sea',
    name: 'Kerala',
    shortName: 'Kerala',
    state: 'Kerala',
    corridorName: 'Malabar Upwelling Shelf',
    chartNumber: 'Chart IN-220',
    chartTitle: 'Chart IN-220: Malabar Coast & Cochin Fairway',
    chartMeta: "Scale 1:150,000 · Mercator Projection · LAT 9°50'N – 10°20'N · LONG 76°00'E – 76°25'E",
    beaconStatus: 'Acoustic Beacon 35 Online',
    shelfProfile: 'upwelling',
    shelfDescription: 'Nutrient-rich clayey silt shelf famous for the seasonal Chakara mud banks.',
    maxDepth: 40,
    maxDist: 20,
    depthGraticules: [0, 10, 20, 30],
    distMarkers: [5, 10, 15, 20],
    defaultZoneId: 'willingdon-fairway',
    subZoneIds: ['willingdon-fairway', 'vypeen-grounds', 'munambam-estuary']
  },
  {
    id: 'deendayal-kandla',
    portId: 'deendayal-kandla',
    regionId: 'arabian-sea',
    name: 'Gujarat',
    shortName: 'Gujarat',
    state: 'Gujarat',
    corridorName: 'Kutch Macro-Tidal Shelf',
    chartNumber: 'Chart IN-203',
    chartTitle: 'Chart IN-203: Gulf of Kutch & Kandla Approaches',
    chartMeta: "Scale 1:150,000 · Mercator Projection · LAT 22°40'N – 23°10'N · LONG 69°15'E – 70°20'E",
    beaconStatus: 'Acoustic Beacon 19 Online',
    shelfProfile: 'macrotidal',
    shelfDescription: 'Dynamic macro-tidal sand banks, shoals, and shallow mangrove mudflats.',
    maxDepth: 30,
    maxDist: 25,
    depthGraticules: [0, 10, 20, 30],
    distMarkers: [5, 10, 15, 20, 25],
    defaultZoneId: 'kandla-fairway-buoy',
    subZoneIds: ['kandla-fairway-buoy', 'tuna-creek-shoals', 'mandvi-bank']
  },
  {
    id: 'port-blair',
    portId: 'port-blair',
    regionId: 'andaman-nicobar',
    name: 'Andaman & Nicobar',
    shortName: 'Andaman',
    state: 'Andaman & Nicobar',
    corridorName: 'Andaman Oceanic Trench',
    chartNumber: 'Chart IN-404',
    chartTitle: 'Chart IN-404: South Andaman Basin & Ten Degree Trench',
    chartMeta: "Scale 1:300,000 · Mercator Projection · LAT 10°00'N – 11°55'N · LONG 92°20'E – 92°55'E",
    beaconStatus: 'Acoustic Beacon 91 Online',
    shelfProfile: 'trench',
    shelfDescription: 'Narrow coral reef fringe dropping rapidly into abyssal oceanic depths (>180m).',
    maxDepth: 200,
    maxDist: 45,
    depthGraticules: [0, 50, 100, 150, 200],
    distMarkers: [10, 20, 30, 40],
    defaultZoneId: 'port-blair-haddo',
    subZoneIds: ['port-blair-haddo', 'ross-island-roads', 'ten-degree-channel-bank']
  },
  {
    id: 'kavaratti',
    portId: 'kavaratti',
    regionId: 'lakshadweep',
    name: 'Lakshadweep',
    shortName: 'Lakshadweep',
    state: 'Lakshadweep',
    corridorName: 'Coral Atoll Pinnacle Shelf',
    chartNumber: 'Chart IN-272',
    chartTitle: 'Chart IN-272: Lakshadweep Sea & Suheli Atoll Bank',
    chartMeta: "Scale 1:200,000 · Mercator Projection · LAT 10°00'N – 10°55'N · LONG 72°10'E – 73°45'E",
    beaconStatus: 'Acoustic Beacon 23 Online',
    shelfProfile: 'atoll',
    shelfDescription: 'Shallow live coral lagoons with sheer underwater atoll drop-offs into the deep sea.',
    maxDepth: 140,
    maxDist: 60,
    depthGraticules: [0, 30, 60, 90, 120],
    distMarkers: [10, 25, 40, 55],
    defaultZoneId: 'kavaratti-lagoon-reef',
    subZoneIds: ['kavaratti-lagoon-reef', 'suheli-par-bank', 'andrott-passage']
  }
]

export const getCorridorByPortId = (portId) => {
  return CORRIDORS.find((c) => c.portId === portId) || CORRIDORS[0]
}

export const getCorridorByZoneId = (zoneId) => {
  return CORRIDORS.find((c) => c.subZoneIds.includes(zoneId)) || CORRIDORS[0]
}
