# Generated from src/lib/zones.js

ALL_ZONES = [
    {
        "id": "digha",
        "name": "Digha",
        "sector_code": "WB-01",
        "port_id": "kolkata-haldia",
        "region_id": "bay-of-bengal",
        "distance_offshore": "8 km",
        "sounding_depth": 12,
        "seabed": "Fine estuarine silt & clay",
        "coordinates": "21°37'N, 87°31'E",
        "lat": 21.6167,
        "lng": 87.5167,
        "coastal_district": "Purba Medinipur",
        "harbor_name": "Digha Mohana Jetty",
        "fleet_type": "Mechanized gillnetters & small trawlers",
        "base_sst": 28.6,
        "base_chlorophyll": 1.5,
        "base_wind": 18,
        "base_wave": 1.1,
        "near_protected_area": False,
        "peak_catch": 620,
        "seasonal_catch_index": [
            340,
            360,
            410,
            480,
            520,
            560,
            600,
            620,
            580,
            500,
            420,
            370
        ],
        "description": ""
    },
    {
        "id": "shankarpur",
        "name": "Shankarpur",
        "sector_code": "WB-02",
        "port_id": "kolkata-haldia",
        "region_id": "bay-of-bengal",
        "distance_offshore": "11 km",
        "sounding_depth": 16,
        "seabed": "Compacted sandy mud",
        "coordinates": "21°38'N, 87°35'E",
        "lat": 21.6333,
        "lng": 87.5833,
        "coastal_district": "Purba Medinipur",
        "harbor_name": "Shankarpur Principal Fishing Harbour",
        "fleet_type": "Commercial trawler fleet (10-15m)",
        "base_sst": 28.3,
        "base_chlorophyll": 1.7,
        "base_wind": 20,
        "base_wave": 1.2,
        "near_protected_area": False,
        "peak_catch": 580,
        "seasonal_catch_index": [
            320,
            350,
            390,
            460,
            500,
            540,
            580,
            560,
            520,
            460,
            400,
            350
        ],
        "description": ""
    },
    {
        "id": "junput",
        "name": "Junput",
        "sector_code": "WB-03",
        "port_id": "kolkata-haldia",
        "region_id": "bay-of-bengal",
        "distance_offshore": "14 km",
        "sounding_depth": 18,
        "seabed": "Soft estuarine mudflat margin",
        "coordinates": "21°43'N, 87°49'E",
        "lat": 21.7167,
        "lng": 87.8167,
        "coastal_district": "Purba Medinipur",
        "harbor_name": "Junput Fish Landing Centre",
        "fleet_type": "Motorized nauka & small trawlers",
        "base_sst": 28.9,
        "base_chlorophyll": 1.9,
        "base_wind": 16,
        "base_wave": 0.9,
        "near_protected_area": False,
        "peak_catch": 490,
        "seasonal_catch_index": [
            280,
            310,
            340,
            400,
            440,
            470,
            490,
            480,
            450,
            390,
            330,
            300
        ],
        "description": ""
    },
    {
        "id": "sagar-island",
        "name": "Sagar Island",
        "sector_code": "WB-04",
        "port_id": "kolkata-haldia",
        "region_id": "bay-of-bengal",
        "distance_offshore": "6 km",
        "sounding_depth": 24,
        "seabed": "Tidal channel scour & silt",
        "coordinates": "21°39'N, 88°02'E",
        "lat": 21.65,
        "lng": 88.0333,
        "coastal_district": "South 24 Parganas",
        "harbor_name": "Sagar Roads Anchorage",
        "fleet_type": "Traditional country craft & beach seines",
        "base_sst": 28.1,
        "base_chlorophyll": 2.2,
        "base_wind": 22,
        "base_wave": 1.4,
        "near_protected_area": True,
        "peak_catch": 530,
        "seasonal_catch_index": [
            310,
            330,
            370,
            430,
            470,
            510,
            530,
            520,
            490,
            420,
            360,
            320
        ],
        "description": ""
    },
    {
        "id": "frazerganj",
        "name": "Frazerganj",
        "sector_code": "WB-05",
        "port_id": "kolkata-haldia",
        "region_id": "bay-of-bengal",
        "distance_offshore": "18 km",
        "sounding_depth": 21,
        "seabed": "Outer estuary sandy bar",
        "coordinates": "21°34'N, 88°15'E",
        "lat": 21.5667,
        "lng": 88.25,
        "coastal_district": "South 24 Parganas",
        "harbor_name": "Frazerganj Fishing Harbour",
        "fleet_type": "Deep-sea mechanized trawlers (15-20m)",
        "base_sst": 28.4,
        "base_chlorophyll": 1.8,
        "base_wind": 24,
        "base_wave": 1.5,
        "near_protected_area": True,
        "peak_catch": 710,
        "seasonal_catch_index": [
            390,
            420,
            480,
            560,
            620,
            670,
            710,
            690,
            640,
            550,
            470,
            420
        ],
        "description": ""
    },
    {
        "id": "kakdwip",
        "name": "Kakdwip",
        "sector_code": "WB-06",
        "port_id": "kolkata-haldia",
        "region_id": "bay-of-bengal",
        "distance_offshore": "3 km",
        "sounding_depth": 29,
        "seabed": "Muriganga river bed & deep scour",
        "coordinates": "21°52'N, 88°11'E",
        "lat": 21.8667,
        "lng": 88.1833,
        "coastal_district": "South 24 Parganas",
        "harbor_name": "Kakdwip Jetty",
        "fleet_type": "Riverine gillnetters & wooden dinghies",
        "base_sst": 29.1,
        "base_chlorophyll": 2.4,
        "base_wind": 14,
        "base_wave": 0.7,
        "near_protected_area": False,
        "peak_catch": 440,
        "seasonal_catch_index": [
            250,
            270,
            310,
            360,
            390,
            420,
            440,
            430,
            400,
            350,
            300,
            270
        ],
        "description": ""
    },
    {
        "id": "paradip-outer",
        "name": "Paradip Outer Anchorage",
        "sector_code": "OD-01",
        "port_id": "paradip",
        "region_id": "bay-of-bengal",
        "distance_offshore": "14 km",
        "sounding_depth": 22,
        "seabed": "Terrigenous coastal sand & clay",
        "coordinates": "20°15'N, 86°42'E",
        "lat": 20.25,
        "lng": 86.7,
        "coastal_district": "Jagatsinghpur",
        "harbor_name": "Paradip Marine Fishing Harbour",
        "fleet_type": "Steel hull multiday trawlers",
        "base_sst": 28.2,
        "base_chlorophyll": 1.8,
        "base_wind": 21,
        "base_wave": 1.3,
        "near_protected_area": False,
        "peak_catch": 650,
        "seasonal_catch_index": [
            350,
            380,
            430,
            500,
            550,
            600,
            650,
            630,
            580,
            510,
            430,
            380
        ],
        "description": ""
    },
    {
        "id": "mahanadi-mouth",
        "name": "Mahanadi River Mouth",
        "sector_code": "OD-02",
        "port_id": "paradip",
        "region_id": "bay-of-bengal",
        "distance_offshore": "7 km",
        "sounding_depth": 15,
        "seabed": "Alluvial river plume delta",
        "coordinates": "20°17'N, 86°44'E",
        "lat": 20.2833,
        "lng": 86.7333,
        "coastal_district": "Kendrapara",
        "harbor_name": "False Point Light Jetty",
        "fleet_type": "Mechanized gillnetters & fiber craft",
        "base_sst": 28.5,
        "base_chlorophyll": 2.3,
        "base_wind": 18,
        "base_wave": 1,
        "near_protected_area": True,
        "peak_catch": 590,
        "seasonal_catch_index": [
            310,
            340,
            390,
            460,
            510,
            550,
            590,
            570,
            530,
            450,
            380,
            330
        ],
        "description": ""
    },
    {
        "id": "jatadhari-estuary",
        "name": "Jatadhari Estuary",
        "sector_code": "OD-03",
        "port_id": "paradip",
        "region_id": "bay-of-bengal",
        "distance_offshore": "9 km",
        "sounding_depth": 18,
        "seabed": "Siliceous muddy sand",
        "coordinates": "20°12'N, 86°36'E",
        "lat": 20.2,
        "lng": 86.6,
        "coastal_district": "Jagatsinghpur",
        "harbor_name": "Nuagarh Fish Landing Quay",
        "fleet_type": "Motorized FRP boats (8-10m)",
        "base_sst": 28.4,
        "base_chlorophyll": 1.9,
        "base_wind": 19,
        "base_wave": 1.1,
        "near_protected_area": False,
        "peak_catch": 520,
        "seasonal_catch_index": [
            280,
            310,
            350,
            410,
            460,
            490,
            520,
            500,
            470,
            400,
            340,
            300
        ],
        "description": ""
    },
    {
        "id": "vizag-dolphins-nose",
        "name": "Dolphin’s Nose Deepwater",
        "sector_code": "AP-01",
        "port_id": "visakhapatnam",
        "region_id": "bay-of-bengal",
        "distance_offshore": "12 km",
        "sounding_depth": 42,
        "seabed": "Steep continental slope rocky gravel",
        "coordinates": "17°40'N, 83°19'E",
        "lat": 17.6667,
        "lng": 83.3167,
        "coastal_district": "Visakhapatnam",
        "harbor_name": "Visakhapatnam Fishing Harbour",
        "fleet_type": "Deep-sea steel tuna longliners (20m+)",
        "base_sst": 28,
        "base_chlorophyll": 1.3,
        "base_wind": 22,
        "base_wave": 1.4,
        "near_protected_area": False,
        "peak_catch": 780,
        "seasonal_catch_index": [
            420,
            460,
            520,
            610,
            680,
            740,
            780,
            750,
            700,
            620,
            510,
            450
        ],
        "description": ""
    },
    {
        "id": "gangavaram-roads",
        "name": "Gangavaram Roadstead",
        "sector_code": "AP-02",
        "port_id": "visakhapatnam",
        "region_id": "bay-of-bengal",
        "distance_offshore": "8 km",
        "sounding_depth": 35,
        "seabed": "Heavy mineral sand & granite bedrock",
        "coordinates": "17°37'N, 83°14'E",
        "lat": 17.6167,
        "lng": 83.2333,
        "coastal_district": "Anakapalli",
        "harbor_name": "Gangavaram Landing Center",
        "fleet_type": "Mechanized trawlers & fiber teppa",
        "base_sst": 28.1,
        "base_chlorophyll": 1.5,
        "base_wind": 20,
        "base_wave": 1.2,
        "near_protected_area": False,
        "peak_catch": 610,
        "seasonal_catch_index": [
            330,
            360,
            410,
            480,
            540,
            580,
            610,
            590,
            550,
            470,
            400,
            350
        ],
        "description": ""
    },
    {
        "id": "rishikonda-bank",
        "name": "Rishikonda Coastal Shelf",
        "sector_code": "AP-03",
        "port_id": "visakhapatnam",
        "region_id": "bay-of-bengal",
        "distance_offshore": "5 km",
        "sounding_depth": 26,
        "seabed": "Coarse coastal sand",
        "coordinates": "17°46'N, 83°23'E",
        "lat": 17.7667,
        "lng": 83.3833,
        "coastal_district": "Visakhapatnam",
        "harbor_name": "Bheemunipatnam Jetty",
        "fleet_type": "Traditional motorized katamaran",
        "base_sst": 28.3,
        "base_chlorophyll": 1.7,
        "base_wind": 18,
        "base_wave": 1.1,
        "near_protected_area": False,
        "peak_catch": 520,
        "seasonal_catch_index": [
            270,
            300,
            340,
            410,
            460,
            490,
            520,
            500,
            470,
            400,
            330,
            290
        ],
        "description": ""
    },
    {
        "id": "chennai-kasimedu",
        "name": "Kasimedu Harbour Approaches",
        "sector_code": "TN-01",
        "port_id": "chennai",
        "region_id": "bay-of-bengal",
        "distance_offshore": "10 km",
        "sounding_depth": 28,
        "seabed": "Siliceous muddy sand",
        "coordinates": "13°07'N, 80°18'E",
        "lat": 13.1167,
        "lng": 80.3,
        "coastal_district": "Chennai",
        "harbor_name": "Kasimedu Fishing Harbour",
        "fleet_type": "Commercial mechanized trawlers (500+ fleet)",
        "base_sst": 28.7,
        "base_chlorophyll": 1.6,
        "base_wind": 21,
        "base_wave": 1.3,
        "near_protected_area": False,
        "peak_catch": 720,
        "seasonal_catch_index": [
            390,
            430,
            490,
            570,
            630,
            680,
            720,
            700,
            650,
            560,
            480,
            410
        ],
        "description": ""
    },
    {
        "id": "ennore-shoals",
        "name": "Ennore Outer Shoals",
        "sector_code": "TN-02",
        "port_id": "chennai",
        "region_id": "bay-of-bengal",
        "distance_offshore": "14 km",
        "sounding_depth": 25,
        "seabed": "Sandy mud with shell fragments",
        "coordinates": "13°16'N, 80°22'E",
        "lat": 13.2667,
        "lng": 80.3667,
        "coastal_district": "Tiruvallur",
        "harbor_name": "Kamarajar Marine Basin",
        "fleet_type": "Mechanized trawlers & FRP boats",
        "base_sst": 28.8,
        "base_chlorophyll": 1.8,
        "base_wind": 20,
        "base_wave": 1.2,
        "near_protected_area": False,
        "peak_catch": 560,
        "seasonal_catch_index": [
            300,
            330,
            380,
            440,
            490,
            530,
            560,
            540,
            510,
            430,
            370,
            320
        ],
        "description": ""
    },
    {
        "id": "marina-outer-bank",
        "name": "Marina Outer Bank",
        "sector_code": "TN-03",
        "port_id": "chennai",
        "region_id": "bay-of-bengal",
        "distance_offshore": "6 km",
        "sounding_depth": 19,
        "seabed": "Medium coastal quartz sand",
        "coordinates": "13°03'N, 80°18'E",
        "lat": 13.05,
        "lng": 80.3,
        "coastal_district": "Chennai",
        "harbor_name": "Nochikuppam Fish Landing Jetty",
        "fleet_type": "Traditional motorized fiberglass vallams",
        "base_sst": 28.6,
        "base_chlorophyll": 1.7,
        "base_wind": 19,
        "base_wave": 1.1,
        "near_protected_area": False,
        "peak_catch": 480,
        "seasonal_catch_index": [
            260,
            290,
            330,
            380,
            430,
            460,
            480,
            470,
            440,
            370,
            310,
            270
        ],
        "description": ""
    },
    {
        "id": "sassoon-dock-offshore",
        "name": "Sassoon Dock Offshore Grounds",
        "sector_code": "MH-01",
        "port_id": "mumbai",
        "region_id": "arabian-sea",
        "distance_offshore": "12 km",
        "sounding_depth": 26,
        "seabed": "Basaltic trap rock mud & fine sand",
        "coordinates": "18°53'N, 72°46'E",
        "lat": 18.8833,
        "lng": 72.7667,
        "coastal_district": "Mumbai City",
        "harbor_name": "Sassoon Docks Fish Landing Terminal",
        "fleet_type": "Mechanized trawlers & bag-netters (Dol-net)",
        "base_sst": 27.9,
        "base_chlorophyll": 2.1,
        "base_wind": 22,
        "base_wave": 1.4,
        "near_protected_area": False,
        "peak_catch": 810,
        "seasonal_catch_index": [
            450,
            490,
            560,
            650,
            720,
            770,
            810,
            790,
            740,
            640,
            540,
            470
        ],
        "description": ""
    },
    {
        "id": "mumbai-floating-light",
        "name": "Mumbai Floating Light Fairway",
        "sector_code": "MH-02",
        "port_id": "mumbai",
        "region_id": "arabian-sea",
        "distance_offshore": "18 km",
        "sounding_depth": 34,
        "seabed": "Dark olive-green silty mud",
        "coordinates": "18°50'N, 72°40'E",
        "lat": 18.8333,
        "lng": 72.6667,
        "coastal_district": "Mumbai Suburban",
        "harbor_name": "Ferry Wharf (Bhaucha Dhakka)",
        "fleet_type": "Deepwater trawlers & container pilot craft",
        "base_sst": 27.8,
        "base_chlorophyll": 1.9,
        "base_wind": 24,
        "base_wave": 1.6,
        "near_protected_area": False,
        "peak_catch": 740,
        "seasonal_catch_index": [
            410,
            450,
            510,
            590,
            660,
            710,
            740,
            720,
            670,
            580,
            490,
            430
        ],
        "description": ""
    },
    {
        "id": "alibaug-shoals",
        "name": "Alibaug Shoals",
        "sector_code": "MH-03",
        "port_id": "mumbai",
        "region_id": "arabian-sea",
        "distance_offshore": "9 km",
        "sounding_depth": 18,
        "seabed": "Rocky ledge & coastal sand",
        "coordinates": "18°39'N, 72°50'E",
        "lat": 18.65,
        "lng": 72.8333,
        "coastal_district": "Raigad",
        "harbor_name": "Kashid & Revdanda Jetty",
        "fleet_type": "Traditional wooden gillnetters",
        "base_sst": 28.2,
        "base_chlorophyll": 2.3,
        "base_wind": 20,
        "base_wave": 1.2,
        "near_protected_area": False,
        "peak_catch": 630,
        "seasonal_catch_index": [
            340,
            380,
            430,
            500,
            560,
            600,
            630,
            610,
            570,
            490,
            410,
            360
        ],
        "description": ""
    },
    {
        "id": "willingdon-fairway",
        "name": "Willingdon Deepwater Approach",
        "sector_code": "KL-01",
        "port_id": "cochin",
        "region_id": "arabian-sea",
        "distance_offshore": "14 km",
        "sounding_depth": 32,
        "seabed": "Clayey silt rich in upwelling nutrients",
        "coordinates": "9°58'N, 76°08'E",
        "lat": 9.9667,
        "lng": 76.1333,
        "coastal_district": "Ernakulam",
        "harbor_name": "Kochi International Marine Terminal",
        "fleet_type": "Steel ocean purse seiners (25m)",
        "base_sst": 28.4,
        "base_chlorophyll": 2.8,
        "base_wind": 23,
        "base_wave": 1.5,
        "near_protected_area": False,
        "peak_catch": 890,
        "seasonal_catch_index": [
            490,
            540,
            620,
            720,
            800,
            850,
            890,
            870,
            810,
            700,
            590,
            510
        ],
        "description": ""
    },
    {
        "id": "vypeen-grounds",
        "name": "Vypeen Coastal Fishing Bank",
        "sector_code": "KL-02",
        "port_id": "cochin",
        "region_id": "arabian-sea",
        "distance_offshore": "8 km",
        "sounding_depth": 22,
        "seabed": "Mud bank formation (Chakara zone)",
        "coordinates": "10°01'N, 76°12'E",
        "lat": 10.0167,
        "lng": 76.2,
        "coastal_district": "Ernakulam",
        "harbor_name": "Kalamukku Fish Harbour (Vypeen)",
        "fleet_type": "Mechanized ring-seine boats & inboard trawlers",
        "base_sst": 28.2,
        "base_chlorophyll": 3.2,
        "base_wind": 20,
        "base_wave": 1.2,
        "near_protected_area": False,
        "peak_catch": 840,
        "seasonal_catch_index": [
            460,
            510,
            580,
            680,
            750,
            800,
            840,
            820,
            760,
            660,
            550,
            480
        ],
        "description": ""
    },
    {
        "id": "munambam-estuary",
        "name": "Munambam River Shelf",
        "sector_code": "KL-03",
        "port_id": "cochin",
        "region_id": "arabian-sea",
        "distance_offshore": "11 km",
        "sounding_depth": 26,
        "seabed": "Periyar river mouth estuarine mud",
        "coordinates": "10°11'N, 76°09'E",
        "lat": 10.1833,
        "lng": 76.15,
        "coastal_district": "Thrissur / Ernakulam",
        "harbor_name": "Munambam Mini Fishing Harbour",
        "fleet_type": "Multiday trawlers with GPS sonars",
        "base_sst": 28.5,
        "base_chlorophyll": 2.6,
        "base_wind": 21,
        "base_wave": 1.3,
        "near_protected_area": False,
        "peak_catch": 760,
        "seasonal_catch_index": [
            420,
            460,
            530,
            610,
            680,
            730,
            760,
            740,
            690,
            600,
            500,
            440
        ],
        "description": ""
    },
    {
        "id": "kandla-fairway-buoy",
        "name": "Kandla Fairway Approaches",
        "sector_code": "GJ-01",
        "port_id": "deendayal-kandla",
        "region_id": "arabian-sea",
        "distance_offshore": "16 km",
        "sounding_depth": 18,
        "seabed": "Macro-tidal sand waves & dynamic shoals",
        "coordinates": "22°53'N, 70°07'E",
        "lat": 22.8833,
        "lng": 70.1167,
        "coastal_district": "Kutch",
        "harbor_name": "Kandla Marine Harbor",
        "fleet_type": "Mechanized trawlers & dhows",
        "base_sst": 27.4,
        "base_chlorophyll": 2.2,
        "base_wind": 26,
        "base_wave": 1.7,
        "near_protected_area": False,
        "peak_catch": 820,
        "seasonal_catch_index": [
            450,
            490,
            560,
            650,
            730,
            780,
            820,
            800,
            750,
            650,
            540,
            470
        ],
        "description": ""
    },
    {
        "id": "tuna-creek-shoals",
        "name": "Tuna Creek Shoals",
        "sector_code": "GJ-02",
        "port_id": "deendayal-kandla",
        "region_id": "arabian-sea",
        "distance_offshore": "10 km",
        "sounding_depth": 14,
        "seabed": "Mangrove mudflats & silty flats",
        "coordinates": "22°58'N, 70°05'E",
        "lat": 22.9667,
        "lng": 70.0833,
        "coastal_district": "Kutch",
        "harbor_name": "Tuna Port Jetty",
        "fleet_type": "Artisanal tidal gillnetters",
        "base_sst": 27.8,
        "base_chlorophyll": 2.6,
        "base_wind": 22,
        "base_wave": 1.1,
        "near_protected_area": True,
        "peak_catch": 580,
        "seasonal_catch_index": [
            310,
            340,
            390,
            460,
            520,
            550,
            580,
            560,
            520,
            450,
            380,
            330
        ],
        "description": ""
    },
    {
        "id": "mandvi-bank",
        "name": "Mandvi Offshore Bank",
        "sector_code": "GJ-03",
        "port_id": "deendayal-kandla",
        "region_id": "arabian-sea",
        "distance_offshore": "12 km",
        "sounding_depth": 22,
        "seabed": "Coarse sand & shell gravel",
        "coordinates": "22°48'N, 69°20'E",
        "lat": 22.8,
        "lng": 69.3333,
        "coastal_district": "Kutch",
        "harbor_name": "Mandvi Historic Port",
        "fleet_type": "Traditional wooden Kotia craft",
        "base_sst": 27.2,
        "base_chlorophyll": 2,
        "base_wind": 24,
        "base_wave": 1.5,
        "near_protected_area": False,
        "peak_catch": 690,
        "seasonal_catch_index": [
            380,
            410,
            470,
            550,
            610,
            660,
            690,
            670,
            630,
            540,
            460,
            400
        ],
        "description": ""
    },
    {
        "id": "port-blair-haddo",
        "name": "Haddo Basin Deep Drop-Off",
        "sector_code": "AN-01",
        "port_id": "port-blair",
        "region_id": "andaman-nicobar",
        "distance_offshore": "15 km",
        "sounding_depth": 85,
        "seabed": "Volcanic basalt & coral terrace",
        "coordinates": "11°41'N, 92°43'E",
        "lat": 11.6833,
        "lng": 92.7167,
        "coastal_district": "South Andaman",
        "harbor_name": "Junglighat Fishing Harbour",
        "fleet_type": "Multiday pelagic longliners (18-24m)",
        "base_sst": 29.2,
        "base_chlorophyll": 0.9,
        "base_wind": 20,
        "base_wave": 1.4,
        "near_protected_area": False,
        "peak_catch": 920,
        "seasonal_catch_index": [
            510,
            560,
            640,
            740,
            820,
            880,
            920,
            900,
            840,
            730,
            610,
            530
        ],
        "description": ""
    },
    {
        "id": "ross-island-roads",
        "name": "Ross Island Outer Roadstead",
        "sector_code": "AN-02",
        "port_id": "port-blair",
        "region_id": "andaman-nicobar",
        "distance_offshore": "8 km",
        "sounding_depth": 48,
        "seabed": "Fringing reef limestone gravel",
        "coordinates": "11°40'N, 92°47'E",
        "lat": 11.6667,
        "lng": 92.7833,
        "coastal_district": "South Andaman",
        "harbor_name": "Phoenix Bay Marine Jetty",
        "fleet_type": "Fiberglass speed skiffs",
        "base_sst": 29.1,
        "base_chlorophyll": 1.1,
        "base_wind": 18,
        "base_wave": 1.2,
        "near_protected_area": True,
        "peak_catch": 610,
        "seasonal_catch_index": [
            330,
            360,
            420,
            480,
            540,
            580,
            610,
            590,
            550,
            470,
            400,
            350
        ],
        "description": ""
    },
    {
        "id": "ten-degree-channel-bank",
        "name": "Ten Degree Channel Edge",
        "sector_code": "AN-03",
        "port_id": "port-blair",
        "region_id": "andaman-nicobar",
        "distance_offshore": "35 km",
        "sounding_depth": 180,
        "seabed": "Oceanic deep trench abyss",
        "coordinates": "10°00'N, 92°30'E",
        "lat": 10,
        "lng": 92.5,
        "coastal_district": "Nicobar",
        "harbor_name": "Car Nicobar Marine Station",
        "fleet_type": "Industrial tuna exploratory vessels",
        "base_sst": 29.4,
        "base_chlorophyll": 0.8,
        "base_wind": 26,
        "base_wave": 2.1,
        "near_protected_area": False,
        "peak_catch": 1100,
        "seasonal_catch_index": [
            600,
            670,
            760,
            880,
            980,
            1050,
            1100,
            1070,
            1000,
            870,
            730,
            630
        ],
        "description": ""
    },
    {
        "id": "kavaratti-lagoon-reef",
        "name": "Kavaratti Lagoon & Outer Reef",
        "sector_code": "LD-01",
        "port_id": "kavaratti",
        "region_id": "lakshadweep",
        "distance_offshore": "4 km",
        "sounding_depth": 18,
        "seabed": "Coral sand & live Porites reef shelf",
        "coordinates": "10°34'N, 72°38'E",
        "lat": 10.5667,
        "lng": 72.6333,
        "coastal_district": "Lakshadweep",
        "harbor_name": "Kavaratti Passenger & Fish Jetty",
        "fleet_type": "Traditional pole-and-line tuna craft (Odi)",
        "base_sst": 28.9,
        "base_chlorophyll": 1.1,
        "base_wind": 19,
        "base_wave": 1.2,
        "near_protected_area": True,
        "peak_catch": 750,
        "seasonal_catch_index": [
            410,
            460,
            520,
            600,
            670,
            720,
            750,
            730,
            680,
            590,
            500,
            430
        ],
        "description": ""
    },
    {
        "id": "suheli-par-bank",
        "name": "Suheli Par Submerged Bank",
        "sector_code": "LD-02",
        "port_id": "kavaratti",
        "region_id": "lakshadweep",
        "distance_offshore": "52 km",
        "sounding_depth": 42,
        "seabed": "Oceanic submerged atoll coral pinnacle",
        "coordinates": "10°05'N, 72°17'E",
        "lat": 10.0833,
        "lng": 72.2833,
        "coastal_district": "Lakshadweep",
        "harbor_name": "Suheli Valiyakara Temporary Anchorage",
        "fleet_type": "High-speed tuna catcher boats",
        "base_sst": 28.7,
        "base_chlorophyll": 1.2,
        "base_wind": 22,
        "base_wave": 1.6,
        "near_protected_area": False,
        "peak_catch": 880,
        "seasonal_catch_index": [
            480,
            530,
            610,
            710,
            790,
            840,
            880,
            860,
            800,
            690,
            580,
            500
        ],
        "description": ""
    },
    {
        "id": "andrott-passage",
        "name": "Andrott Oceanic Passage",
        "sector_code": "LD-03",
        "port_id": "kavaratti",
        "region_id": "lakshadweep",
        "distance_offshore": "15 km",
        "sounding_depth": 120,
        "seabed": "Steep oceanic plateau drop-off",
        "coordinates": "10°49'N, 73°41'E",
        "lat": 10.8167,
        "lng": 73.6833,
        "coastal_district": "Lakshadweep",
        "harbor_name": "Andrott Breakwater Jetty",
        "fleet_type": "Mechanized longline skiffs",
        "base_sst": 29,
        "base_chlorophyll": 1,
        "base_wind": 21,
        "base_wave": 1.4,
        "near_protected_area": False,
        "peak_catch": 810,
        "seasonal_catch_index": [
            440,
            490,
            560,
            650,
            720,
            780,
            810,
            790,
            740,
            640,
            530,
            460
        ],
        "description": ""
    }
]
